# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180326_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wished_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hired_date',
            new_name='birth_date',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='post',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborations', to='users.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.User'),
        ),
    ]
