# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180328_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hearted_by',
            field=models.ManyToManyField(related_name='hearted_posts', to='users.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='version',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
