# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180328_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hearted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_posts', to='users.User'),
        ),
    ]
